### ISSUE TITLE
Add Warning

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/user-activity-watcher#17]
- The bot should warn before unassignment. 
- Warning doesn't seem to work. 
- Also should close draft pull. 
- Ref: https://github.com/ubiquity/pay.ubq.fi/issues/267

**Comment by gentlementlegen** [comment]
The warning should work better once https://github.com/ubiquibot/user-activity-watcher/pull/13 is merged in.

**Comment by 0x4007** [comment]
Warning seems to work but closing pulls no.

**Comment by gentlementlegen** [comment]
Closing pulls coming in https://github.com/ubiquibot/command-start-stop/issues/27
