### ISSUE TITLE
Update deadline and reminders on time label change

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/user-activity-watcher#4]
When the time label in changed, the deadline and reminder schedules should be updated to reflect the new values.

What should be done:
- on a time label tag change, update the deadline
- on a time label tag removal, delete the entry
- add related tests

**Comment by 0x4007** [comment]
I never had a situation where I felt that this needs to be implemented. I am leaning to voting against this proposal but please elaborate further.

**Comment by gentlementlegen** [comment]
@0x4007 I didn't see that case either but I thought it'd be a failsafe and I believe this should be handled if we change the time for the task while someone is assigned.
